version: '3.10'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=qazwsx123456
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=prova
      - DB_USER=abdulmonaim
      - DB_PASS=qazwsx123456 
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=prova
      - POSTGRES_USER=abdulmonaim
      - POSTGRES_PASSWORD=qazwsx123456
 
